version: '3'

services:
  app:
    container_name: app-server
    build: 
      context: .
      dockerfile: /front/Dockerfile
    ports:
      - 3000:3000

  proxy:
    container_name: proxy-server
    build: 
      context: .
      dockerfile: /proxy/Dockerfile
    ports:
      - 5000:5000

  api:
    container_name: api-server
    build: 
      context: .
      dockerfile: /api/Dockerfile
    ports:
      - 4000:4000

  pi:
    container_name: pi-side
    build:
      context: .
      dockerfile: /node/Dockerfile